# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: docapply
services:
  postgres:
    extends:
      file: postgres.yml
      service: postgres
  keycloak:
    extends:
      file: keycloak.yml
      service: keycloak
